version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    image: rio96/videoflix
    command: gunicorn videoflix.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/usr/src/app/media

  worker:
    image: rio96/videoflix-worker
    command: python manage.py rqworker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./media:/usr/src/app/media

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    depends_on:
      - web

volumes:
  postgres_data:
