version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: videoflix_db
      POSTGRES_USER: rio96
      POSTGRES_PASSWORD: Stampertje
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    image: rio96/videoflix
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    image: rio96/videoflix-worker
    command: python manage.py rqworker
    depends_on:
      - redis

volumes:
  postgres_data:
